service: pydex-database
frameworkVersion: "3"

package:
  patterns:
    - "!node_modules/**"
    - "!auth-sls"
    - "!.serverless"
    - "!.gitignore"
    - "!package.json"
    - "!package-lock.json"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1

custom:
  # user table
  userTableName: ${self:service}-users-table-${self:provider.stage}
  googleUserIdIndexName: ${self:service}-google-id-index-${self:provider.stage}

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: api_token
            AttributeType: S
          - AttributeName: google_user_id
            AttributeType: S
        KeySchema:
          - AttributeName: api_token
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.googleUserIdIndexName}
            KeySchema:
              - AttributeName: google_user_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
